[package]
name = "mk"

license = "MIT"
version = "0.0.1"
edition = "2018"

[dependencies]
pwd = "1.3"
pam-sys = "0.5"
nix = "0.22"
shadow = "0.0.1"
rpassword = "5.0"

libcrypt-sys = { path = "libcrypt-sys" }
