cargo-features = ["strip"]

[package]
name = "mk"

license = "MIT"
version = "0.0.1"
edition = "2018"
authors = ["Sachin Cherian <sachinctl@protonmail.com>"]

[profile.release]
lto = true
strip = true
codegen-units = 1

[dependencies]
libc = "0.2"

pam-sys = "0.5"
shadow = "0.0.1"

rpassword = "5.0"
thiserror = "1.0"

mk-pwd = { path = "crates/mk-pwd" }
libcrypt-sys = { path = "crates/libcrypt-sys" }
