cargo-features = ["strip"]

[workspace]
members = [
    "crates/mk-common",
    "crates/mk-crypt",
    "crates/mk-pam",
    "crates/mk-pwd"
]

[package]
name = "mk"

license = "MIT"
version = "0.0.1"
edition = "2018"
authors = ["Sachin Cherian <sachinctl@protonmail.com>"]

[profile.release]
lto = true
strip = true
codegen-units = 1

[dependencies]
libc = "0.2"

clap = "3.0.0-beta.4"
colored = "2"
rpassword = "5.0"
thiserror = "1.0"

shadow = "0.0.1"
mk-pwd = { path = "crates/mk-pwd" }
mk-pam = { path = "crates/mk-pam" }
mk-crypt = { path = "crates/mk-crypt" }
mk-common = { path = "crates/mk-common" }
