[package]
name = "mk-pwd"

license = "MIT"
version = "0.0.1"
authors = ["Sachin Cherian <sachinctl@protonmail.com>"]

edition = "2021"
rust-version = "1.56"

[dependencies]
libc = "0.2"
lazy_static = "1.4"
mk-common = { path = "../mk-common" }
