[package]
name = "mk-pam"

build = "build/main.rs"
license = "MIT"
version = "0.0.1"
edition = "2018"
authors = ["Sachin Cherian <sachinctl@protonmail.com>"]

[dependencies]
libc = "0.2"
num_enum = "0.5"
thiserror = "1.0"

[build-dependencies]
bindgen = "0.59"
